# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '3.7'

networks:
  test:
    name: traceflow

services:
  ca_producers:
    image: hyperledger/fabric-ca:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-producers
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=4400
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:14400
    ports:
      - "4400:4400"
      - "14400:14400"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../organizations/fabric-ca/producers:/etc/hyperledger/fabric-ca-server
    container_name: ca_producers
    networks:
      - test

  ca_distributors:
    image: hyperledger/fabric-ca:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-distributors
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=5500
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:15500
    ports:
      - "5500:5500"
      - "15500:15500"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../organizations/fabric-ca/distributors:/etc/hyperledger/fabric-ca-server
    container_name: ca_distributors
    networks:
      - test

  ca_retailers:
    image: hyperledger/fabric-ca:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-retailers
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=6600
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:16600
    ports:
      - "6600:6600"
      - "16600:16600"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../organizations/fabric-ca/retailers:/etc/hyperledger/fabric-ca-server
    container_name: ca_retailers
    networks:
      - test

  ca_customers:
    image: hyperledger/fabric-ca:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-customers
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7700
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:17700
    ports:
      - "7700:7700"
      - "17700:17700"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../organizations/fabric-ca/customers:/etc/hyperledger/fabric-ca-server
    container_name: ca_customers
    networks:
      - test

  ca_suppliers:
    image: hyperledger/fabric-ca:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-suppliers
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=8800
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:18800
    ports:
      - "8800:8800"
      - "18800:18800"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../organizations/fabric-ca/suppliers:/etc/hyperledger/fabric-ca-server
    container_name: ca_suppliers
    networks:
      - test

  ca_orderer1:
    image: hyperledger/fabric-ca:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-orderer1
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=2200
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:12200
    ports:
      - "2200:2200"
      - "12200:12200"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../organizations/fabric-ca/orderer1:/etc/hyperledger/fabric-ca-server
    container_name: ca_orderer1
    networks:
      - test
  ca_orderer2:
    image: hyperledger/fabric-ca:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-orderer2
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=2201
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:12201
    ports:
      - "2201:2201"
      - "12201:12201"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../organizations/fabric-ca/orderer2:/etc/hyperledger/fabric-ca-server
    container_name: ca_orderer2
    networks:
      - test


